{{ if .Values.serviceAccounts.diagnose.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "submariner.diagnoseServiceAccountName" . }}
{{ if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "submariner.diagnoseServiceAccountName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - create
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
    verbs:
      - get
      - list
  - apiGroups:
      - submariner.io
    resources:
      - '*'
    verbs:
      - get
      - list
  - apiGroups:
      - multicluster.x-k8s.io
    resources:
      - '*'
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "submariner.diagnoseServiceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "submariner.diagnoseServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "submariner.diagnoseServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "submariner.diagnoseServiceAccountName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - nodes
      - services
    verbs:
      - get
      - list
  - apiGroups:
      - submariner.io
    resources:
      - clusterglobalegressips
      - globalegressips
      - globalingressips
    verbs:
      - get
      - list
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
  - apiGroups:
      - multicluster.x-k8s.io
    resources:
      - serviceexports
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "submariner.diagnoseServiceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "submariner.diagnoseServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "submariner.diagnoseServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocp-{{ template "submariner.diagnoseServiceAccountName" . }}
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocp-{{ template "submariner.diagnoseServiceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocp-{{ template "submariner.diagnoseServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "submariner.diagnoseServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
{{ end }}
