{{ if .Values.serviceAccounts.networkPluginSyncer.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "submariner.networkPluginSyncerServiceAccountName" . }}
{{ if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "submariner.networkPluginSyncerServiceAccountName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - submariner.io
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "submariner.networkPluginSyncerServiceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "submariner.networkPluginSyncerServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "submariner.networkPluginSyncerServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocp-{{ template "submariner.networkPluginSyncerServiceAccountName" . }}
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocp-{{ template "submariner.networkPluginSyncerServiceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocp-{{ template "submariner.networkPluginSyncerServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "submariner.networkPluginSyncerServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
{{ end }}
