apiVersion: submariner.io/v1alpha1
kind: Broker
metadata:
  name: submariner-broker
spec:
  components:
  - service-discovery
  - connectivity
  defaultGlobalnetClusterSize: 65536
  globalnetCIDRRange: 242.0.0.0/8
