{{ if .Values.serviceAccounts.admin.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "submariner-k8s-broker.adminServiceAccountName" . }}
{{ if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "submariner-k8s-broker.adminServiceAccountName" . }}
rules:
  - apiGroups:
      - submariner.io
    resources:
      - clusters
      - endpoints
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - secrets
      - configmaps
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - create
      - get
      - list
      - delete
  - apiGroups:
      - multicluster.x-k8s.io
    resources:
      - '*'
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
      - delete
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
      - endpointslices/restricted
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "submariner-k8s-broker.adminServiceAccountName" . }}-{{ template "submariner-k8s-broker.adminServiceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "submariner-k8s-broker.adminServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "submariner-k8s-broker.adminServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
{{ end }}
