apiVersion: v1
kind: ServiceAccount
metadata:
  name: submariner-initializer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: submariner-initializer
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
    resourceNames:
      - ocp-submariner-diagnose
      - ocp-submariner-gateway
      - ocp-submariner-globalnet
      - ocp-submariner-lighthouse
      - ocp-submariner-lighthouse
      - ocp-submariner-networkplugin
      - ocp-submariner-operator
      - ocp-submariner-routeagent
    verbs:
      - delete
  - apiGroups:
      - operator.openshift.io
    resources:
      - dnses
    verbs:
      - update
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: submariner-initializer-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: submariner-initializer
subjects:
  - kind: ServiceAccount
    name: submariner-initializer
    namespace: {{ .Release.Namespace }}
